import type { GenerationProvenance } from "@/lib/schema";

import styles from "./artefacts.module.css";

export function Provenance({ value }: { value: GenerationProvenance | null }) {
  // A JSON column: trust the type for its shape, but not a hand-edited row for its
  // presence.
  if (!value?.model || !Array.isArray(value.documents)) {
    return null;
  }
  const pieces =
    value.documents.length === 1
      ? "1 piece of material"
      : `${String(value.documents.length)} pieces of material`;
  const warning = typeof value.warning === "string" && value.warning.trim() ? value.warning : null;
  return (
    <p className={styles.provenance}>
      {`Generated by ${value.model} from ${pieces}`}
      {warning ? <span className={styles.provenanceWarning}>{warning}</span> : null}
    </p>
  );
}
