import type { GenerationProvenance, GenerationUsage } from "@/lib/schema";

import styles from "./artefacts.module.css";

/** "$1.31 · 32 calls", or null when the calls behind it were never priced. */
function costLine(usage: GenerationUsage | undefined): string | null {
  if (typeof usage?.cost_usd !== "number") {
    return null;
  }
  const calls = usage.calls === 1 ? "1 call" : `${String(usage.calls)} calls`;
  return `$${usage.cost_usd.toFixed(2)} · ${calls}`;
}

export function Provenance({ value }: { value: GenerationProvenance | null }) {
  // A JSON column: trust the type for its shape, but not a hand-edited row for its
  // presence.
  if (!value?.model || !Array.isArray(value.documents)) {
    return null;
  }
  const pieces =
    value.documents.length === 1
      ? "1 piece of material"
      : `${String(value.documents.length)} pieces of material`;
  const warning = typeof value.warning === "string" && value.warning.trim() ? value.warning : null;
  const cost = costLine(value.usage);
  const total = costLine(value.usage_total);
  return (
    <p className={styles.provenance}>
      {`Generated by ${value.model} from ${pieces}`}
      {cost ? ` · ${cost}` : ""}
      {total ? ` · ${total} total` : ""}
      {warning ? <span className={styles.provenanceWarning}>{warning}</span> : null}
    </p>
  );
}
