/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. It does not reach Directus, so it stays up while Directus is down.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is calling. A caller a `students` row points at is a student; anyone else is a tutor.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Student Login */
        post: operations["add_student_login_api_students__student_id__login_post"];
        /**
         * Remove Student Login
         * @description The login goes; the student's work stays.
         */
        delete: operations["remove_student_login_api_students__student_id__login_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Student Password */
        post: operations["set_student_password_api_students__student_id__login_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Document
         * @description File the material as pending and answer immediately; the row carries the outcome.
         */
        post: operations["add_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Document
         * @description Read the material again — what a tutor's Retry on a failed row does.
         */
        post: operations["reprocess_document_api_documents__document_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Job
         * @description Queue a generation and answer immediately; the job row carries the outcome.
         */
        post: operations["create_job_api_jobs__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CallerRole
         * @enum {string}
         */
        CallerRole: "tutor" | "student";
        /** Document */
        Document: {
            /** Title */
            title: string;
            kind: components["schemas"]["DocumentKind"];
            /** Source Url */
            source_url?: string | null;
            /** File */
            file?: string | null;
            /** Text */
            text?: string | null;
            /** Student */
            student?: string | null;
            /** Session */
            session?: string | null;
            /** @default pending */
            status: components["schemas"]["DocumentStatus"];
            /** Error */
            error?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "transcript" | "web_page" | "question_bank" | "upload";
        /** DocumentRequest */
        DocumentRequest: {
            /** Student Id */
            student_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Title */
            title?: string | null;
            source: components["schemas"]["DocumentSourceRequest"];
        };
        DocumentSourceRequest: components["schemas"]["FileSourceRequest"] | components["schemas"]["UrlSourceRequest"] | components["schemas"]["TextSourceRequest"];
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "processing" | "ready" | "failed";
        /** FileSourceRequest */
        FileSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
        };
        /** GenerationJob */
        GenerationJob: {
            kind: components["schemas"]["GenerationKind"];
            /** Student */
            student?: string | null;
            /** @default queued */
            status: components["schemas"]["JobStatus"];
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /** Output Collection */
            output_collection?: string | null;
            /** Output Id */
            output_id?: string | null;
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /**
         * GenerationKind
         * @enum {string}
         */
        GenerationKind: "homework" | "feedback" | "plan";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * Identity
         * @description Who is calling, and the student row they are, when they are one.
         */
        Identity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            role: components["schemas"]["CallerRole"];
            /** Student Id */
            student_id?: string | null;
        };
        /** JobRequest */
        JobRequest: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Document Ids
             * @default []
             */
            document_ids: string[];
            /** Instructions */
            instructions?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PasswordRequest */
        PasswordRequest: {
            /** Password */
            password: string;
        };
        /** StudentLogin */
        StudentLogin: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
        };
        /** TextSourceRequest */
        TextSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** UrlSourceRequest */
        UrlSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
        };
    };
    add_student_login_api_students__student_id__login_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentLogin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_student_login_api_students__student_id__login_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_student_password_api_students__student_id__login_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_api_documents__document_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["GenerationKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
