/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. It does not reach Directus, so it stays up while Directus is down.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is calling: an admin by their policies, a student by a `students` row, else a tutor.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Admin Health
         * @description Every service the practice runs on. A service that is down is `ok: false`, not an error.
         */
        get: operations["read_admin_health_api_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tutors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tutors */
        get: operations["read_tutors_api_admin_tutors_get"];
        put?: never;
        /** Add Tutor */
        post: operations["add_tutor_api_admin_tutors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tutors/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Tutor Password */
        post: operations["set_tutor_password_api_admin_tutors__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tutors/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Tutor
         * @description A tutor who still has students is a 409: reassigning them comes first.
         */
        delete: operations["delete_tutor_api_admin_tutors__user_id__delete"];
        options?: never;
        head?: never;
        /** Change Tutor Status */
        patch: operations["change_tutor_status_api_admin_tutors__user_id__patch"];
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Admin Jobs */
        get: operations["read_admin_jobs_api_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Student Login */
        post: operations["add_student_login_api_students__student_id__login_post"];
        /**
         * Remove Student Login
         * @description The login goes; the student's work stays.
         */
        delete: operations["remove_student_login_api_students__student_id__login_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Student Password */
        post: operations["set_student_password_api_students__student_id__login_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Document
         * @description File the material as pending and answer immediately; the row carries the outcome.
         */
        post: operations["add_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Document
         * @description Read the material again — what a tutor's Retry on a failed row does.
         */
        post: operations["reprocess_document_api_documents__document_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Job
         * @description Queue a generation and answer immediately; the job row carries the outcome.
         */
        post: operations["create_job_api_jobs__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/typeset/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Typst
         * @description A live preview while a tutor writes. Source that will not compile is a 422.
         */
        post: operations["preview_typst_api_typeset_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/typeset/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Canonical
         * @description A canonical structure previewed in the house style. Nothing is read or stored.
         */
        post: operations["render_canonical_api_typeset_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homework/{homework_id}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Homework
         * @description Compile the row's `content` again. A failure sets `compile_error` and keeps the old PDF.
         */
        post: operations["compile_homework_api_homework__homework_id__compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Paper
         * @description Render the stored structure again — what a tutor runs after reviewing an extraction.
         *
         *     Maths the compiler refuses is repaired against its diagnostics before it gives up.
         */
        post: operations["render_paper_api_papers__paper_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/worksheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paper Worksheet Pdf
         * @description Some of a paper's questions as a worksheet: the tutor's remix, filed as a PDF.
         */
        post: operations["paper_worksheet_pdf_api_papers__paper_id__worksheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminHealth */
        AdminHealth: {
            directus: components["schemas"]["DirectusHealth"];
            api: components["schemas"]["ApiHealth"];
            typeset: components["schemas"]["TypesetHealth"];
            generation: components["schemas"]["GenerationHealth"];
            counts: components["schemas"]["HealthCounts"];
        };
        /**
         * AdminJob
         * @description A generation job as the whole-practice listing shows it.
         */
        AdminJob: {
            job: components["schemas"]["GenerationJob"];
            /** Student Name */
            student_name?: string | null;
            /** Tutor Email */
            tutor_email?: string | null;
        };
        /** ApiHealth */
        ApiHealth: {
            /**
             * Ok
             * @default true
             */
            ok?: boolean;
            /** Version */
            version: string;
        };
        /**
         * CallerRole
         * @enum {string}
         */
        CallerRole: "admin" | "tutor" | "student";
        /** CanonicalMarkScheme */
        CanonicalMarkScheme: {
            /** Title */
            title: string;
            /**
             * Questions
             * @default []
             */
            questions?: components["schemas"]["CanonicalMarkSchemeQuestion"][];
        };
        /** CanonicalMarkSchemePart */
        CanonicalMarkSchemePart: {
            /** Label */
            label: string;
            /** Answer */
            answer: string;
            /** Marks */
            marks?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** CanonicalMarkSchemeQuestion */
        CanonicalMarkSchemeQuestion: {
            /** Number */
            number: string;
            /**
             * Parts
             * @default []
             */
            parts?: components["schemas"]["CanonicalMarkSchemePart"][];
            /** Answer */
            answer?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CanonicalMarkup
         * @description Typst markup on its own, for a fragment that has no structure to walk.
         */
        CanonicalMarkup: {
            /** Text */
            text: string;
        };
        /** CanonicalPaper */
        CanonicalPaper: {
            /** Title */
            title: string;
            /** Source */
            source?: string | null;
            /** Board */
            board?: string | null;
            /** Year */
            year?: number | null;
            /** Time Minutes */
            time_minutes?: number | null;
            /** Total Marks */
            total_marks?: number | null;
            /** Instructions */
            instructions?: string | null;
            /**
             * Questions
             * @default []
             */
            questions?: components["schemas"]["CanonicalQuestion"][];
        };
        /** CanonicalPart */
        CanonicalPart: {
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Marks */
            marks?: number | null;
            /** Answer Lines */
            answer_lines?: number | null;
            /**
             * Parts
             * @default []
             */
            parts?: components["schemas"]["CanonicalSubPart"][];
        };
        /** CanonicalQuestion */
        CanonicalQuestion: {
            /** Number */
            number: string;
            /** Stem */
            stem?: string | null;
            /** Marks */
            marks?: number | null;
            /**
             * Parts
             * @default []
             */
            parts?: components["schemas"]["CanonicalPart"][];
            /** Answer Lines */
            answer_lines?: number | null;
        };
        /**
         * CanonicalSubPart
         * @description `(a)` then `(i)`: parts nest one level, so a part of a part holds none of its own.
         */
        CanonicalSubPart: {
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Marks */
            marks?: number | null;
            /** Answer Lines */
            answer_lines?: number | null;
        };
        /** CanonicalWorksheet */
        CanonicalWorksheet: {
            /** Title */
            title: string;
            /** Student */
            student?: string | null;
            /** Due */
            due?: string | null;
            /** Intro */
            intro?: string | null;
            /**
             * Questions
             * @default []
             */
            questions?: components["schemas"]["CanonicalQuestion"][];
        };
        /** DirectusHealth */
        DirectusHealth: {
            /** Ok */
            ok: boolean;
            /** Version */
            version?: string | null;
            license?: components["schemas"]["DirectusLicense"] | null;
        };
        /**
         * DirectusLicense
         * @description `/license`, which only an admin may read.
         */
        DirectusLicense: {
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
        };
        /** Document */
        Document: {
            /** Title */
            title: string;
            kind: components["schemas"]["DocumentKind"];
            /** Source Url */
            source_url?: string | null;
            /** File */
            file?: string | null;
            /** Text */
            text?: string | null;
            /** Student */
            student?: string | null;
            /** Session */
            session?: string | null;
            /** @default pending */
            status?: components["schemas"]["DocumentStatus"];
            /** Error */
            error?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "transcript" | "web_page" | "question_bank" | "upload";
        /** DocumentRequest */
        DocumentRequest: {
            /** Student Id */
            student_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Title */
            title?: string | null;
            source: components["schemas"]["DocumentSourceRequest"];
        };
        DocumentSourceRequest: components["schemas"]["FileSourceRequest"] | components["schemas"]["UrlSourceRequest"] | components["schemas"]["TextSourceRequest"];
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "processing" | "ready" | "failed";
        /** FileSourceRequest */
        FileSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
        };
        /** GenerationHealth */
        GenerationHealth: {
            /** Backend */
            backend: string;
            /** Model */
            model: string;
        };
        /** GenerationJob */
        GenerationJob: {
            kind: components["schemas"]["GenerationKind"];
            /** Student */
            student?: string | null;
            /** @default queued */
            status?: components["schemas"]["JobStatus"];
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /** Output Collection */
            output_collection?: string | null;
            /** Output Id */
            output_id?: string | null;
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /**
         * GenerationKind
         * @enum {string}
         */
        GenerationKind: "homework" | "feedback" | "plan" | "paper_extract";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HealthCounts */
        HealthCounts: {
            /**
             * Tutors
             * @default 0
             */
            tutors?: number;
            /**
             * Students
             * @default 0
             */
            students?: number;
            /**
             * Documents
             * @default 0
             */
            documents?: number;
            /**
             * Jobs Running
             * @default 0
             */
            jobs_running?: number;
        };
        /** Homework */
        Homework: {
            /**
             * Student
             * Format: uuid
             */
            student: string;
            /** Session */
            session?: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** @default markdown */
            format?: components["schemas"]["HomeworkFormat"];
            /** Pdf */
            pdf?: string | null;
            /** Submission File */
            submission_file?: string | null;
            /** Compile Error */
            compile_error?: string | null;
            /** Due On */
            due_on?: string | null;
            /** @default draft */
            status?: components["schemas"]["HomeworkStatus"];
            /** Submission */
            submission?: string | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Generated From */
            generated_from?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /**
         * HomeworkFormat
         * @enum {string}
         */
        HomeworkFormat: "markdown" | "typst";
        /**
         * HomeworkStatus
         * @enum {string}
         */
        HomeworkStatus: "draft" | "assigned" | "submitted" | "marked";
        /**
         * Identity
         * @description Who is calling, and the student row they are, when they are one.
         */
        Identity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            role: components["schemas"]["CallerRole"];
            /** Student Id */
            student_id?: string | null;
        };
        /** JobRequest */
        JobRequest: {
            /** Student Id */
            student_id?: string | null;
            /**
             * Document Ids
             * @default []
             */
            document_ids?: string[];
            /** Instructions */
            instructions?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** @default markdown */
            format?: components["schemas"]["HomeworkFormat"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MarkSchemeRenderRequest */
        MarkSchemeRenderRequest: {
            /**
             * Output
             * @default svg
             * @enum {string}
             */
            output?: "svg" | "source";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mark_scheme";
            document: components["schemas"]["CanonicalMarkScheme"];
        };
        /** MarkupRenderRequest */
        MarkupRenderRequest: {
            /**
             * Output
             * @default svg
             * @enum {string}
             */
            output?: "svg" | "source";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "markup";
            document: components["schemas"]["CanonicalMarkup"];
        };
        /** Paper */
        Paper: {
            /** Title */
            title: string;
            /** Source */
            source?: string | null;
            /** Board */
            board?: string | null;
            /** Year */
            year?: number | null;
            /** Time Minutes */
            time_minutes?: number | null;
            /** Total Marks */
            total_marks?: number | null;
            /** Instructions */
            instructions?: string | null;
            /** @default draft */
            status?: components["schemas"]["PaperStatus"];
            /** Document */
            document?: string | null;
            /** Rendered Pdf */
            rendered_pdf?: string | null;
            /** Mark Scheme Pdf */
            mark_scheme_pdf?: string | null;
            /** Structure */
            structure?: {
                [key: string]: unknown;
            } | null;
            /** Mark Scheme */
            mark_scheme?: {
                [key: string]: unknown;
            } | null;
            /** Generated From */
            generated_from?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Date Created */
            date_created?: string | null;
            /** Date Updated */
            date_updated?: string | null;
            /** User Created */
            user_created?: string | null;
            /** User Updated */
            user_updated?: string | null;
        };
        /** PaperRenderRequest */
        PaperRenderRequest: {
            /**
             * Output
             * @default svg
             * @enum {string}
             */
            output?: "svg" | "source";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "paper";
            document: components["schemas"]["CanonicalPaper"];
        };
        /**
         * PaperStatus
         * @enum {string}
         */
        PaperStatus: "draft" | "reviewed" | "archived";
        /** PasswordRequest */
        PasswordRequest: {
            /** Password */
            password: string;
        };
        /** QuestionRenderRequest */
        QuestionRenderRequest: {
            /**
             * Output
             * @default svg
             * @enum {string}
             */
            output?: "svg" | "source";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "question";
            document: components["schemas"]["CanonicalQuestion"];
            mark_scheme?: components["schemas"]["CanonicalMarkSchemeQuestion"] | null;
        };
        /** StudentLogin */
        StudentLogin: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
        };
        /** TextSourceRequest */
        TextSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** TutorAccount */
        TutorAccount: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Students
             * @default 0
             */
            students?: number;
            /** Last Access */
            last_access?: string | null;
        };
        /** TutorRequest */
        TutorRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /**
         * TutorStatus
         * @enum {string}
         */
        TutorStatus: "active" | "suspended";
        /** TutorStatusRequest */
        TutorStatusRequest: {
            status: components["schemas"]["TutorStatus"];
        };
        /** TypesetHealth */
        TypesetHealth: {
            /** Ok */
            ok: boolean;
            /** Url */
            url: string;
        };
        /**
         * TypstPreview
         * @description One SVG per page, ready to drop into the tutor's editor.
         */
        TypstPreview: {
            /** Pages */
            pages: string[];
        };
        /**
         * TypstRender
         * @description `pages` is empty when `output` is `source`, and `source` is null when it is `svg`.
         */
        TypstRender: {
            /** Pages */
            pages: string[];
            /** Source */
            source: string | null;
        };
        /** TypstRequest */
        TypstRequest: {
            /** Source */
            source: string;
        };
        /** UrlSourceRequest */
        UrlSourceRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorksheetRenderRequest */
        WorksheetRenderRequest: {
            /**
             * Output
             * @default svg
             * @enum {string}
             */
            output?: "svg" | "source";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "worksheet";
            document: components["schemas"]["CanonicalWorksheet"];
        };
        /** WorksheetRequest */
        WorksheetRequest: {
            /** Question Numbers */
            question_numbers: string[];
            /** Student Id */
            student_id?: string | null;
            /** Title */
            title?: string | null;
            /** Due */
            due?: string | null;
        };
        /**
         * WorksheetResult
         * @description A worksheet as it was rendered: the Typst it compiled from, and the filed PDF.
         */
        WorksheetResult: {
            /** Source */
            source: string;
            /**
             * Pdf File Id
             * Format: uuid
             */
            pdf_file_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
        };
    };
    read_admin_health_api_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHealth"];
                };
            };
        };
    };
    read_tutors_api_admin_tutors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorAccount"][];
                };
            };
        };
    };
    add_tutor_api_admin_tutors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tutor_password_api_admin_tutors__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tutor_api_admin_tutors__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_tutor_status_api_admin_tutors__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_admin_jobs_api_admin_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_student_login_api_students__student_id__login_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentLogin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_student_login_api_students__student_id__login_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_student_password_api_students__student_id__login_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_api_documents__document_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["GenerationKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_typst_api_typeset_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypstRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypstPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_canonical_api_typeset_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperRenderRequest"] | components["schemas"]["MarkSchemeRenderRequest"] | components["schemas"]["WorksheetRenderRequest"] | components["schemas"]["QuestionRenderRequest"] | components["schemas"]["MarkupRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypstRender"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_homework_api_homework__homework_id__compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homework_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Homework"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_paper_api_papers__paper_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_worksheet_pdf_api_papers__paper_id__worksheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorksheetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
